### ISSUE TITLE
Script compatibility with Node.js Newer runtime

### ISSUE THREAD

**Issue by Nagarajantv** [newrelic-experimental/nr-bulk-ssl-checker#3]
Hi @phawxby / @jsbnr :

The **Synthetic script as part of this project will need to be upgraded/refactored to be compatible with Node.js new runtime(Node 16.x) **in the scripted API Monitor.

With Legacy Runtime(Node 10.x) the scripted api monitor works fine, but when we run the same script with Node.js new runtime we are getting error 'ERR_GOT_REQUEST_ERROR' from the **got** library used by Node.js new runtime. 

Considering that Node.js legacy runtime will be deprecated soon at New Relic end, script refactoring to be compatible with new runtime is definitely needed.

```
RequestError: The `body`, `json` and `form` options are mutually exclusive
    at Request._destroy (/app/synthetics-node-api-runtime/.yarn/cache/got-npm-11.8.6-89e7cd5d67-bbc783578a.zip/node_modules/got/dist/source/core/index.js:1386:21)
    at _destroy (node:internal/streams/destroy:102:25)
    at Request.destroy (node:internal/streams/destroy:64:5)
    at /app/synthetics-node-api-runtime/.yarn/cache/got-npm-11.8.6-89e7cd5d67-bbc783578a.zip/node_modules/got/dist/source/core/index.js:354:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Request._finalizeBody (/app/synthetics-node-api-runtime/.yarn/cache/got-npm-11.8.6-89e7cd5d67-bbc783578a.zip/node_modules/got/dist/source/core/index.js:719:23)
.................
.................
.................
    at getPromiseOrStream (/app/synthetics-node-api-runtime/.yarn/cache/got-npm-11.8.6-89e7cd5d67-bbc783578a.zip/node_modules/got/dist/source/create.js:43:121) {
  code: 'ERR_GOT_REQUEST_ERROR',
  timings: undefined
}
```

**Comment by jsbnr** [comment]
Thanks for raising, we'll look into this.

**Comment by Nagarajantv** [comment]
Thanks @jsbnr
